name: Sanity

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      -master

jobs:
  build:
    name: Say hi from CI
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Write a message
        run: >-
          echo Hi from CI! This is just a sanity check, and the only intended purpose of this job
          is to have a job that always successes.