name: Testing

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      -master

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Build unit tests
        run: |
          cd tests/unit
          cmake -S . -B build
          cmake --build build
      - name: Run unit tests
        run: |
          cd tests/unit/build
          ctest
      - name: Unit tests logs
        run: |
          cat tests/unit/build/Testing/Temporary/LastTest.log
