name: Testing

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      -master

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Set up C++
        run: |
          sudo apt install -y --no-install-recommends build-essential
          g++ --version
      - name: Run tests
        run: |
          ./run_tests.sh
        working-directory: tests
