name: Sanity

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      -master

jobs:
  build:
    name: Hi from CI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Build tests
        run: |
          cd tests
          cmake -S . -B build
          cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest
