name: Testing

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      -master

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Build & run unit tests
        run: |
          cd tests/unit
          cmake -S . -B build
          cmake --build build
          cd build
          ctest
      - name: Run pwd
        run: pwd
